"use client"
import { useRef, useState, useLayoutEffect } from 'react'
import { Canvas, useThree, useFrame } from '@react-three/fiber'
import { useGLTF, Html, OrbitControls, Environment, ContactShadows, Preload, ScrollControls, useScroll } from '@react-three/drei'
import { gsap } from 'gsap'
import { TimelineLite } from 'gsap'


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: stPixel (https://sketchfab.com/innasparrow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-icon-pins-8a4747df22054de7908664e41b0670ed
Title: 3D icon PINS
*/

function Model(props: any) {
  const { nodes, materials }: any = useGLTF('/models3D/mapa/mapa.gltf')
  const [windowWidth, setWindowWidth] = useState(
    typeof window !== 'undefined' ? window.innerWidth : 0
  )

  const scrollControl = useScroll()
  const timeline = useRef<TimelineLite | undefined>(undefined)


  const generalGroupRef = useRef<THREE.Group | undefined>(undefined)


  // Html div references
  const page_1_ref = document.getElementById('page-1')
  const page_2_ref = document.getElementById('page-2')
  const page_3_ref = document.getElementById('page-3')
  const page_4_ref = document.getElementById('page-4')
  const page_5_ref = document.getElementById('page-5')
  const page_6_ref = document.getElementById('page-6')
  const page_7_ref = document.getElementById('page-7')
  const page_8_ref = document.getElementById('page-8')
  const page_9_ref = document.getElementById('page-9')
  const page_10_ref = document.getElementById('page-10')
  const page_11_ref = document.getElementById('page-11')
  const page_12_ref = document.getElementById('page-12')

  //MESH MATERIAL
  const item_s = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_s_scale = useRef<THREE.Group | undefined>(undefined)
  const item_1 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_2 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_3 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_4 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_5 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_6 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_7 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_8 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_8_scale = useRef<THREE.Group | undefined>(undefined)
  const item_9 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_10 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_11 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_12 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_12_scale = useRef<THREE.Group | undefined>(undefined)
  const item_13 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_14 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_15 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_16 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_18 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_19 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_19_scale = useRef<THREE.Group | undefined>(undefined)
  const item_20 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_21 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_22 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_23 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_24 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_25 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_26 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_27 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_27_scale = useRef<THREE.Group | undefined>(undefined)
  const item_28 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_29 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_30 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_31 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_32 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_33 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_34 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_35 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_36 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_37 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_38 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_39 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_40 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_41 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_42 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_43 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_44 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_45 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_46 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_47 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_48 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_49 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_50 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_51 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_52 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_52_scale = useRef<THREE.Group | undefined>(undefined)
  const item_53 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_54 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_55 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_56 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_57 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_58 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_59 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_60 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_61 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_62 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_62_scale = useRef<THREE.Group | undefined>(undefined)
  const item_63 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_64 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_65 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_66 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_67 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_68 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_69 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_70 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_71 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_72 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_73 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)

  const item_74 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_75 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_76 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_77 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_78 = useRef<THREE.MeshStandardMaterial | undefined>(undefined)

  const item_f = useRef<THREE.MeshStandardMaterial | undefined>(undefined)
  const item_f_scale = useRef<THREE.Group | undefined>(undefined)








  useLayoutEffect(() => {
    timeline.current = gsap.timeline()
    //MESH MATERIAL
    if (item_s.current) {
      timeline.current.to(item_s.current.color, { r: 1, g: 0, b: 0, duration: 0.2 }, 0.01)
    }
    if (item_s_scale.current) {
      timeline.current.to(item_s_scale.current.scale, { x: item_s_scale.current.scale.x + 0.02, y: item_s_scale.current.scale.y + 0.02, z: item_s_scale.current.scale.z + 0.02, duration: 0.2 }, 0.01)
    }
    if (item_1.current) {
      timeline.current.to(item_1.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.04)
    }
    if (item_2.current) {
      timeline.current.to(item_2.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.07)
    }
    if (item_3.current) {
      timeline.current.to(item_3.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.1)
    }
    if (item_4.current) {
      timeline.current.to(item_4.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.13)
    }
    if (item_5.current) {
      timeline.current.to(item_5.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.13)
    }
    if (item_6.current) {
      timeline.current.to(item_6.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.5)
    }
    if (item_7.current) {
      timeline.current.to(item_7.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.5)
    }
    if (item_8.current) {
      timeline.current.to(item_8.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 0.5)
    }
    if (item_8_scale.current) {
      timeline.current.to(item_8_scale.current.scale, { x: item_8_scale.current.scale.x + 0.1, y: item_8_scale.current.scale.y + 0.1, z: item_8_scale.current.scale.z + 0.1, duration: 0.2 }, 0.5)
    }
    if (item_9.current) {
      timeline.current.to(item_9.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.0)
    }
    if (item_10.current) {
      timeline.current.to(item_10.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.1)
    }
    if (item_11.current) {
      timeline.current.to(item_11.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.2)
    }
    if (item_12.current) {
      timeline.current.to(item_12.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.3)
    }
    if (item_12_scale.current) {
      timeline.current.to(item_12_scale.current.scale, { x: item_12_scale.current.scale.x + 0.1, y: item_12_scale.current.scale.y + 0.1, z: item_12_scale.current.scale.z + 0.1, duration: 0.2 }, 1.3)
    }
    if (item_13.current) {
      timeline.current.to(item_13.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.6)
    }
    if (item_14.current) {
      timeline.current.to(item_14.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.7)
    }
    if (item_15.current) {
      timeline.current.to(item_15.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.8)
    }
    if (item_16.current) {
      timeline.current.to(item_16.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 1.9)
    }
    if (item_18.current) {
      timeline.current.to(item_18.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.0)
    }
    if (item_19.current) {
      timeline.current.to(item_19.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.0)
    }
    if (item_19_scale.current) {
      timeline.current.to(item_19_scale.current.scale, { x: item_19_scale.current.scale.x + 0.1, y: item_19_scale.current.scale.y + 0.1, z: item_19_scale.current.scale.z + 0.1, duration: 0.2 }, 2.0)
    }
    if (item_20.current) {
      timeline.current.to(item_20.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.2)
    }
    if (item_21.current) {
      timeline.current.to(item_21.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.3)
    }
    if (item_22.current) {
      timeline.current.to(item_22.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.4)
    }
    if (item_23.current) {
      timeline.current.to(item_23.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.5)
    }
    if (item_24.current) {
      timeline.current.to(item_24.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.6)
    }
    if (item_25.current) {
      timeline.current.to(item_25.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.7)
    }
    if (item_26.current) {
      timeline.current.to(item_26.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.8)
    }
    if (item_27.current) {
      timeline.current.to(item_27.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 2.9)
    }
    if (item_27_scale.current) {
      timeline.current.to(item_27_scale.current.scale, { x: item_27_scale.current.scale.x + 0.1, y: item_27_scale.current.scale.y + 0.1, z: item_27_scale.current.scale.z + 0.1, duration: 0.2 }, 2.9)
    }
    if (item_28.current) {
      timeline.current.to(item_28.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_29.current) {
      timeline.current.to(item_29.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_30.current) {
      timeline.current.to(item_30.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_31.current) {
      timeline.current.to(item_31.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_32.current) {
      timeline.current.to(item_32.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_33.current) {
      timeline.current.to(item_33.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_34.current) {
      timeline.current.to(item_34.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_35.current) {
      timeline.current.to(item_35.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_36.current) {
      timeline.current.to(item_36.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }
    if (item_37.current) {
      timeline.current.to(item_37.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.1)
    }

    if (item_38.current) {
      timeline.current.to(item_38.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_39.current) {
      timeline.current.to(item_39.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_40.current) {
      timeline.current.to(item_40.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_41.current) {
      timeline.current.to(item_41.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_42.current) {
      timeline.current.to(item_42.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_43.current) {
      timeline.current.to(item_43.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_44.current) {
      timeline.current.to(item_44.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_45.current) {
      timeline.current.to(item_45.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_46.current) {
      timeline.current.to(item_46.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_47.current) {
      timeline.current.to(item_47.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_48.current) {
      timeline.current.to(item_48.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_49.current) {
      timeline.current.to(item_49.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_50.current) {
      timeline.current.to(item_50.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.2)
    }
    if (item_51.current) {
      timeline.current.to(item_51.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.5)
    }
    if (item_52.current) {
      timeline.current.to(item_52.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.5)
    }
    if (item_52_scale.current) {
      timeline.current.to(item_52_scale.current.scale, { x: item_52_scale.current.scale.x + 0.1, y: item_52_scale.current.scale.y + 0.1, z: item_52_scale.current.scale.z + 0.1, duration: 0.2 }, 3.5)
    }
    if (item_53.current) {
      timeline.current.to(item_53.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.8)
    }
    if (item_54.current) {
      timeline.current.to(item_54.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 3.9)
    }
    if (item_55.current) {
      timeline.current.to(item_55.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.0)
    }
    if (item_56.current) {
      timeline.current.to(item_56.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.1)
    }
    if (item_57.current) {
      timeline.current.to(item_57.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.1)
    }
    if (item_58.current) {
      timeline.current.to(item_58.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.1)
    }
    if (item_59.current) {
      timeline.current.to(item_59.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.2)
    }
    if (item_60.current) {
      timeline.current.to(item_60.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.2)
    }
    if (item_61.current) {
      timeline.current.to(item_61.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.3)
    }
    if (item_62.current) {
      timeline.current.to(item_62.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.3)
    }
    if (item_62_scale.current) {
      timeline.current.to(item_62_scale.current.scale, { x: item_62_scale.current.scale.x + 0.1, y: item_62_scale.current.scale.y + 0.1, z: item_62_scale.current.scale.z + 0.1, duration: 0.2 }, 4.3)
    }
    if (item_63.current) {
      timeline.current.to(item_63.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.5)
    }
    if (item_64.current) {
      timeline.current.to(item_64.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.5)
    }
    if (item_65.current) {
      timeline.current.to(item_65.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.6)
    }
    if (item_66.current) {
      timeline.current.to(item_66.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.6)
    }
    if (item_67.current) {
      timeline.current.to(item_67.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.6)
    }

    if (item_68.current) {
      timeline.current.to(item_68.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.7)
    }
    if (item_69.current) {
      timeline.current.to(item_69.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.7)
    }
    if (item_70.current) {
      timeline.current.to(item_70.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.7)
    }
    if (item_71.current) {
      timeline.current.to(item_71.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.8)
    }
    if (item_72.current) {
      timeline.current.to(item_72.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.8)
    }
    if (item_73.current) {
      timeline.current.to(item_73.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.8)
    }

    if (item_74.current) {
      timeline.current.to(item_74.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.9)
    }
    if (item_75.current) {
      timeline.current.to(item_75.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.9)
    }
    if (item_76.current) {
      timeline.current.to(item_76.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 4.9)
    }
    if (item_77.current) {
      timeline.current.to(item_77.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 5.0)
    }
    if (item_78.current) {
      timeline.current.to(item_78.current.color, { r: 0.9, g: 0, b: 0.5, duration: 0.2 }, 5.0)
    }
    if (item_f.current) {
      timeline.current.to(item_f.current.color, { r: 1, g: 0, b: 0, duration: 0.2 }, 5.1)
    }
    if (item_f_scale.current) {
      timeline.current.to(item_f_scale.current.scale, { x: item_f_scale.current.scale.x + 0.02, y: item_f_scale.current.scale.y + 0.02, z: item_f_scale.current.scale.z + 0.02, duration: 0.2 }, 5.1)
    }


    //PAGES

    timeline.current.to(page_1_ref, { opacity: 0, duration: 0.4 }, 0.1)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { y: generalGroupRef.current.position.y + 2, duration: 0.5 }, 0.2)
    }
    {/* Seccion 1*/ }

    timeline.current.to(page_2_ref, { opacity: 1, duration: 0.4 }, 0.4)
    timeline.current.to(page_2_ref, { opacity: 0, duration: 0.4 }, 0.65)

    timeline.current.to(page_3_ref, { opacity: 1, duration: 0.4 }, 0.7)

    timeline.current.to(page_3_ref, { opacity: 0, duration: 0.4 }, 1.0)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { y: generalGroupRef.current.position.y + 5, duration: 0.5 }, 1.1)
    }

    timeline.current.to(page_4_ref, { opacity: 1, duration: 0.4 }, 1.3)

    timeline.current.to(page_4_ref, { opacity: 0, duration: 0.4 }, 1.6)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { x: generalGroupRef.current.position.x - 10, duration: 0.5 }, 1.7)
    }

    //timeline.current.to(page_2_ref, { x: windowWidth < 640 ? 50 : 530, y: windowWidth < 640 ? 70 : -100, duration: 0.3 }, 1.9)
    timeline.current.to(page_5_ref, { opacity: 1, duration: 0.4 }, 1.9)


    //timeline.current.to(page_2_ref, { opacity: 0, duration: 0.4 }, 2.2)
    timeline.current.to(page_5_ref, { opacity: 0, duration: 0.4 }, 2.2)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { x: generalGroupRef.current.position.x + 0.01, y: generalGroupRef.current.position.y + 12, duration: 0.5 }, 2.3)
    }


    {/* Seccion 2*/ }
    timeline.current.to(page_6_ref, { opacity: 1, duration: 0.4 }, 2.5)
    timeline.current.to(page_7_ref, { opacity: 1, duration: 0.4 }, 2.8)

    timeline.current.to(page_6_ref, { opacity: 0, duration: 0.4 }, 3.1)
    timeline.current.to(page_7_ref, { opacity: 0, duration: 0.4 }, 3.1)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { x: generalGroupRef.current.position.x - 4, y: generalGroupRef.current.position.y + 20, duration: 0.5 }, 3.2)
    }

    {/* Seccion 3*/ }
    timeline.current.to(page_8_ref, { opacity: 1, duration: 0.4 }, 3.4)
    timeline.current.to(page_9_ref, { opacity: 1, duration: 0.4 }, 3.7)

    timeline.current.to(page_9_ref, { opacity: 0, duration: 0.3 }, 4.0)
    timeline.current.to(page_8_ref, { x: windowWidth < 640 ? 60 : 730, y: windowWidth < 640 ? 410 : -10, duration: 0.3 }, 4.0)
    timeline.current.to(page_10_ref, { opacity: 1, duration: 0.4 }, 4.0)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { x: generalGroupRef.current.position.x - 13, duration: 0.5 }, 4.0)
    }


    timeline.current.to(page_8_ref, { opacity: 0, duration: 0.4 }, 4.4)
    timeline.current.to(page_10_ref, { opacity: 0, duration: 0.4 }, 4.4)
    if (generalGroupRef.current) {
      timeline.current.to(generalGroupRef.current.position, { x: generalGroupRef.current.position.x + 2, y: generalGroupRef.current.position.y + 28.5, duration: 0.8 }, 4.5)
    }



    {/* Seccion 4*/ }
    timeline.current.to(page_11_ref, { opacity: 1, duration: 0.4 }, 4.7)
    timeline.current.to(page_12_ref, { opacity: 1, duration: 0.4 }, 4.8)





  }, [])

  let changeColor = 'red'

  useFrame(() => {
    if (timeline.current) { timeline.current.seek(scrollControl.offset * timeline.current.duration()) }
  })

  return (
    <group {...props} dispose={null} ref={generalGroupRef} rotation={[0, Math.PI / 2, 0]} >
      <mesh geometry={nodes['1'].geometry} material={nodes['1'].material} position={[0, -0.41, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_1} {...props} />
      </mesh>
      <mesh geometry={nodes['2'].geometry} material={nodes['2'].material} position={[0, -1.628, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_2} {...props} />
      </mesh>
      <mesh geometry={nodes['3'].geometry} material={nodes['3'].material} position={[0, -2.556, 0.391]} rotation={[2.207, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_3} {...props} />
      </mesh>
      <mesh geometry={nodes['4'].geometry} material={nodes['4'].material} position={[0, -2.88, 1.318]} rotation={[-1.381, 0, 0]} scale={[0.37, 0.37, 0.107]}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_4} {...props} />
      </mesh>
      <mesh geometry={nodes['5'].geometry} material={nodes['5'].material} position={[0, -3.091, 2.394]} rotation={[-1.399, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_5} {...props} />
      </mesh>
      <mesh geometry={nodes['6'].geometry} material={nodes['6'].material} position={[0, -3.148, 3.424]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_6} {...props} />
      </mesh>
      <mesh geometry={nodes['7'].geometry} material={nodes['7'].material} position={[0, -2.501, 3.421]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_7} {...props} />
      </mesh>
      <mesh ref={item_8_scale} {...props} geometry={nodes['8-Sphere'].geometry} material={nodes['8-Sphere'].material} position={[0, -1.584, 3.417]} scale={0.41} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_8} {...props} />
      </mesh>
      <mesh geometry={nodes['9'].geometry} material={nodes['9'].material} position={[0, -3.148, 4.476]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_9} {...props} />
      </mesh>
      <mesh geometry={nodes['10'].geometry} material={nodes['10'].material} position={[0, -3.148, 5.55]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_10} {...props} />
      </mesh>
      <mesh geometry={nodes['11'].geometry} material={nodes['11'].material} position={[0, -3.833, 5.58]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_11} {...props} />
      </mesh>
      <mesh ref={item_12_scale} {...props} geometry={nodes['12-Sphere'].geometry} material={nodes['12-Sphere'].material} position={[0, -4.808, 5.593]} scale={0.41} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_12} {...props} />
      </mesh>
      <mesh geometry={nodes['13'].geometry} material={nodes['13'].material} position={[0, -3.259, 6.646]} rotation={[1.779, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_13} {...props} />
      </mesh>
      <mesh geometry={nodes['14'].geometry} material={nodes['14'].material} position={[0, -3.659, 7.665]} rotation={[2.207, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_14} {...props} />
      </mesh>
      <mesh geometry={nodes['15'].geometry} material={nodes['15'].material} position={[0, -4.472, 8.34]} rotation={[2.808, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_15} {...props} />
      </mesh>
      <mesh geometry={nodes['16'].geometry} material={nodes['16'].material} position={[-0.273, -5.411, 8.606]} rotation={[-0.039, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_16} {...props} />
      </mesh>
      <mesh geometry={nodes['18'].geometry} material={nodes['18'].material} position={[0, -5.42, 9.349]} rotation={[1.478, 0, 0]} scale={[0.37, 0.37, 0.107]}   >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_18} {...props} />
      </mesh>
      <mesh ref={item_19_scale} {...props} geometry={nodes['19-Sphere'].geometry} material={nodes['19-Sphere'].material} position={[0, -5.304, 10.388]} scale={0.41}   >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_19} {...props} />
      </mesh>
      <mesh geometry={nodes['20'].geometry} material={nodes['20'].material} position={[-0.273, -6.535, 8.606]} rotation={[0.035, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}   >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_20} {...props} />
      </mesh>
      <mesh geometry={nodes['21'].geometry} material={nodes['21'].material} position={[0, -7.684, 8.471]} rotation={[0.141, 0, 0]} scale={[0.37, 0.37, 0.107]}    >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_21} {...props} />
      </mesh>
      <mesh geometry={nodes['22'].geometry} material={nodes['22'].material} position={[0, -8.689, 8.056]} rotation={[-2.339, 0, 0]} scale={[0.37, 0.37, 0.107]}    >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_22} {...props} />
      </mesh>
      <mesh geometry={nodes['23'].geometry} material={nodes['23'].material} position={[0, -9.237, 7.128]} rotation={[1.256, 0, 0]} scale={[0.37, 0.37, 0.107]}    >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_23} {...props} />
      </mesh>
      <mesh geometry={nodes['24'].geometry} material={nodes['24'].material} position={[0, -9.373, 6.028]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}   >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_24} {...props} />
      </mesh>
      <mesh geometry={nodes['25'].geometry} material={nodes['25'].material} position={[0, -9.373, 4.938]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}    >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_25} {...props} />
      </mesh>
      <mesh geometry={nodes['26'].geometry} material={nodes['26'].material} position={[0, -9.983, 4.953]} scale={[0.37, 0.37, 0.107]}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_26} {...props} />
      </mesh>
      <mesh ref={item_27_scale} {...props} geometry={nodes['27-Sphere'].geometry} material={nodes['27-Sphere'].material} position={[0, -10.88, 4.96]} scale={0.41} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_27} {...props} />
      </mesh>

      <mesh geometry={nodes['28'].geometry} material={nodes['28'].material} position={[0, -9.373, 3.886]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_28} {...props} />
      </mesh>
      <mesh geometry={nodes['29'].geometry} material={nodes['29'].material} position={[0, -9.373, 2.722]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_29} {...props} />
      </mesh>
      <mesh geometry={nodes['30'].geometry} material={nodes['30'].material} position={[0, -9.373, 1.632]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_30} {...props} />
      </mesh>
      <mesh geometry={nodes['31'].geometry} material={nodes['31'].material} position={[0, -9.373, 0.58]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_31} {...props} />
      </mesh>
      <mesh geometry={nodes['32'].geometry} material={nodes['32'].material} position={[0, -9.373, -0.552]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_32} {...props} />
      </mesh>
      <mesh geometry={nodes['33'].geometry} material={nodes['33'].material} position={[0, -9.373, -1.642]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_33} {...props} />
      </mesh>
      <mesh geometry={nodes['34'].geometry} material={nodes['34'].material} position={[0, -9.373, -2.694]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_34} {...props} />
      </mesh>
      <mesh geometry={nodes['35'].geometry} material={nodes['35'].material} position={[0.155, -9.509, -3.926]} rotation={[1.264, 0.01, -3.138]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_35} {...props} />
      </mesh>
      <mesh geometry={nodes['36'].geometry} material={nodes['36'].material} position={[-0.134, -10.014, -4.928]} rotation={[0.835, 0.008, -3.134]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_36} {...props} />
      </mesh>
      <mesh geometry={nodes['37'].geometry} material={nodes['37'].material} position={[-0.273, -10.883, -5.432]} rotation={[0.142, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_37} {...props} />
      </mesh>

      <mesh geometry={nodes['38'].geometry} material={nodes['38'].material} position={[-0.273, -12.041, -5.598]} rotation={[0.103, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_38} {...props} />
      </mesh>
      <mesh geometry={nodes['39'].geometry} material={nodes['39'].material} position={[-0.273, -13.297, -5.639]} rotation={[0.002, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_39} {...props} />
      </mesh>
      <mesh geometry={nodes['40'].geometry} material={nodes['40'].material} position={[-0.273, -14.646, -5.639]} rotation={[0.002, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_40} {...props} />
      </mesh>
      <mesh geometry={nodes['41'].geometry} material={nodes['41'].material} position={[-0.271, -15.912, -5.544]} rotation={[3.042, 0.001, 3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_41} {...props} />
      </mesh>
      <mesh geometry={nodes['42'].geometry} material={nodes['42'].material} position={[-0.117, -16.87, -5.055]} rotation={[-0.902, -0.008, -3.135]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_42} {...props} />
      </mesh>
      <mesh geometry={nodes['43'].geometry} material={nodes['43'].material} position={[0.164, -17.323, -4.118]} rotation={[1.786, 0.01, 3.139]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_43} {...props} />
      </mesh>
      <mesh geometry={nodes['44'].geometry} material={nodes['44'].material} position={[0.476, -17.461, -3.055]} rotation={[1.571, 0.011, -3.141]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_44} {...props} />
      </mesh>
      <mesh geometry={nodes['45'].geometry} material={nodes['45'].material} position={[0, -17.479, -1.95]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_45} {...props} />
      </mesh>
      <mesh geometry={nodes['46'].geometry} material={nodes['46'].material} position={[0, -17.479, -0.86]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_46} {...props} />
      </mesh>
      <mesh geometry={nodes['47'].geometry} material={nodes['47'].material} position={[0, -17.479, 0.271]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_47} {...props} />
      </mesh>
      <mesh geometry={nodes['48'].geometry} material={nodes['48'].material} position={[0, -17.479, 1.323]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_48} {...props} />
      </mesh>
      <mesh geometry={nodes['49'].geometry} material={nodes['49'].material} position={[0, -17.479, 2.413]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_49} {...props} />
      </mesh>
      <mesh geometry={nodes['50'].geometry} material={nodes['50'].material} position={[0, -17.479, 3.577]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_50} {...props} />
      </mesh>
      <mesh geometry={nodes['51'].geometry} material={nodes['51'].material} position={[0, -18.1, 3.583]} scale={[0.37, 0.37, 0.107]}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_51} {...props} />
      </mesh>
      <mesh ref={item_52_scale} {...props} geometry={nodes['52-Sphere'].geometry} material={nodes['52-Sphere'].material} position={[0, -19.129, 3.595]} scale={0.41}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_52} {...props} />
      </mesh>

      <mesh geometry={nodes['53'].geometry} material={nodes['53'].material} position={[0, -17.479, 4.629]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_53} {...props} />
      </mesh>
      <mesh geometry={nodes['54'].geometry} material={nodes['54'].material} position={[0, -17.465, 5.605]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_54} {...props} />
      </mesh>
      <mesh geometry={nodes['55'].geometry} material={nodes['55'].material} position={[0, -17.465, 6.657]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_55} {...props} />
      </mesh>
      <mesh geometry={nodes['56'].geometry} material={nodes['56'].material} position={[0, -17.465, 7.731]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_56} {...props} />
      </mesh>
      <mesh geometry={nodes['57'].geometry} material={nodes['57'].material} position={[0, -17.576, 8.828]} rotation={[1.779, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_57} {...props} />
      </mesh>
      <mesh geometry={nodes['58'].geometry} material={nodes['58'].material} position={[0, -17.975, 9.847]} rotation={[2.207, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_58} {...props} />
      </mesh>

      <mesh geometry={nodes['59'].geometry} material={nodes['59'].material} position={[0, -18.788, 10.522]} rotation={[2.808, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_59} {...props} />
      </mesh>
      <mesh geometry={nodes['60'].geometry} material={nodes['60'].material} position={[-0.273, -19.728, 10.787]} rotation={[-0.039, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_60} {...props} />
      </mesh>
      <mesh geometry={nodes['61'].geometry} material={nodes['61'].material} position={[-0.273, -19.728, 11.537]} rotation={[-1.572, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_61} {...props} />
      </mesh>
      <mesh ref={item_62_scale} {...props} geometry={nodes['62-Sphere'].geometry} material={nodes['62-Sphere'].material} position={[0, -19.713, 12.53]} scale={0.41} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_62} {...props} />
      </mesh>

      <mesh geometry={nodes['63'].geometry} material={nodes['63'].material} position={[-0.273, -20.852, 10.787]} rotation={[0.035, 0.002, -3.131]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_63} {...props} />
      </mesh>
      <mesh geometry={nodes['64'].geometry} material={nodes['64'].material} position={[0, -22, 10.653]} rotation={[0.141, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_64} {...props} />
      </mesh>
      <mesh geometry={nodes['65'].geometry} material={nodes['65'].material} position={[0, -23.005, 10.237]} rotation={[-2.339, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_65} {...props} />
      </mesh>
      <mesh geometry={nodes['66'].geometry} material={nodes['66'].material} position={[0, -23.553, 9.31]} rotation={[1.256, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_66} {...props} />
      </mesh>
      <mesh geometry={nodes['67'].geometry} material={nodes['67'].material} position={[0, -23.689, 8.21]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]}  >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_67} {...props} />
      </mesh>

      <mesh geometry={nodes['68'].geometry} material={nodes['68'].material} position={[0, -23.689, 7.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_68} {...props} />
      </mesh>
      <mesh geometry={nodes['69'].geometry} material={nodes['69'].material} position={[0, -23.689, 6.068]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_69} {...props} />
      </mesh>
      <mesh geometry={nodes['70'].geometry} material={nodes['70'].material} position={[0, -23.689, 4.903]} rotation={[Math.PI / 2, 0, 0]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_70} {...props} />
      </mesh>
      <mesh geometry={nodes['71'].geometry} material={nodes['71'].material} position={[0.005, -23.672, 3.71]} rotation={[-1.531, -0.015, -3.132]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_71} {...props} />
      </mesh>
      <mesh geometry={nodes['72'].geometry} material={nodes['72'].material} position={[-0.006, -23.629, 2.637]} rotation={[-1.531, -0.015, -3.132]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_72} {...props} />
      </mesh>
      <mesh geometry={nodes['73'].geometry} material={nodes['73'].material} position={[-0.016, -23.587, 1.586]} rotation={[-1.531, -0.015, -3.132]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_73} {...props} />
      </mesh>

      <mesh geometry={nodes['74'].geometry} material={nodes['74'].material} position={[-0.026, -23.603, 0.555]} rotation={[1.439, 0.016, 3.134]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_74} {...props} />
      </mesh>
      <mesh geometry={nodes['75'].geometry} material={nodes['75'].material} position={[-0.033, -23.771, -0.528]} rotation={[1.421, 0.017, 3.135]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_75} {...props} />
      </mesh>
      <mesh geometry={nodes['76'].geometry} material={nodes['76'].material} position={[-0.038, -24.057, -1.468]} rotation={[-2.167, -0.018, 3.141]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_76} {...props} />
      </mesh>
      <mesh geometry={nodes['77'].geometry} material={nodes['77'].material} position={[-0.028, -24.969, -1.896]} rotation={[0.04, 0.01, -3.127]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_77} {...props} />
      </mesh>
      <mesh geometry={nodes['78'].geometry} material={nodes['78'].material} position={[-0.01, -26.186, -1.945]} rotation={[0.04, 0.01, -3.127]} scale={[0.37, 0.37, 0.107]} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_78} {...props} />
      </mesh>

      <mesh {...props} ref={item_s_scale} geometry={nodes.start.geometry} position={[-1.815, 1.2, 0.015]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.076} >
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_s} {...props} />
      </mesh>
      <mesh {...props} ref={item_f_scale} geometry={nodes.finish.geometry} position={[-0.995, -27.739, -1.852]} rotation={[-1, 0.174, 1.795]} scale={0.083}>
        <meshStandardMaterial attach="material" roughness={1} metalness={0} ref={item_f} {...props} />
      </mesh>

    </group>
  )
}




function Box(props: any) {
  const ref = useRef<THREE.Group | undefined>(undefined)
  const [hovered, setHover] = useState(false)

  return (
    <mesh
      {...props}
      castShadow
      ref={ref}
      onPointerOver={() => setHover(true)}
      onPointerOut={() => setHover(false)}
    >
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'white' : 'black'} />
      <ambientLight intensity={0.9} />
    </mesh>
  );
}

function Shadows(props: any) {
  const { viewport } = useThree()
  return (
    <mesh receiveShadow scale={[viewport.width, viewport.height, 1]} {...props}>
      <planeGeometry />
      <shadowMaterial transparent opacity={0.5} />
    </mesh>
  )
}



export default function Map(props: any) {
  const cameraRef = useRef<THREE.Group | undefined>(undefined)
  const [windowWidth, setWindowWidth] = useState(
    typeof window !== 'undefined' ? window.innerWidth : 0
  )
  const position_window = windowWidth < 640 ? 20 : 10
  const damping = windowWidth < 640 ? 0.75 : 0.25
  return (
    <Canvas shadows camera={{ fov: 45, position: [0, 0, position_window] }}>


      <ScrollControls pages={10} damping={damping}>
        <Model />
      </ScrollControls>
      <Environment preset='city' />

    </Canvas>
  )
}